services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: YOURPASSWORD
      POSTGRES_DB: replicant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data: